version: '3.8'

services:
  backend:
    container_name: job-posting-backend
    build: ./Backend
    ports:
      - "3015:3015"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=job_portal

  employee-posting:
    container_name: job-posting-employee
    build: ./Employee-posting
    ports:
      - "8025:80"
    depends_on:
      - backend

  hr-posting:
    container_name: job-posting-hr
    build: ./HR-posting
    ports:
      - "8026:80"
    depends_on:
      - backend

  postgres:
    container_name: job-posting-db
    image: postgres:13
    ports:
      - "5410:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: job_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123

volumes:
  postgres_data:
